data = {
  billing_address: {
    address1: None,
    address2: None,
    city: None,
    company: None,
    country: "Vietnam",
    first_name: None,
    id: 1053472936,
    last_name: None,
    phone: None,
    province: None,
    zip: None,
    name: "",
    province_code: None,
    country_code: "VN",
    default: True,
    district: None,
    district_code: None,
    ward: None,
    ward_code: None,
  },
  browser_ip: None,
  buyer_accepts_marketing: False,
  cancel_reason: None,
  cancelled_at: None,
  cart_token: "528cdafeee0c4117a459427d3db99aea",
  checkout_token: "528cdafeee0c4117a459427d3db99aea",
  client_details: {
    accept_language: None,
    browser_ip: None,
    session_hash: None,
    user_agent: None,
    browser_height: None,
    browser_width: None,
  },
  closed_at: None,
  created_at: "2021-10-25T14: 36: 51.947Z",
  currency: "VND",
  customer: {
    accepts_marketing: False,
    addresses: [],
    created_at: "2021-10-25T14: 36: 51.919Z",
    default_address: None,
    email: "guest@haravan.com",
    phone: None,
    first_name: None,
    id: 1053472936,
    last_name: None,
    last_order_id: 1236954857,
    last_order_name: "#100017",
    note: "haipb",
    orders_count: 1,
    state: "disabled",
    tags: None,
    total_spent: 2340000,
    updated_at: "2021-10-26T20: 17: 14Z",
    verified_email: False,
    birthday: None,
    gender: None,
    last_order_date: "2021-10-25T14: 36: 52Z",
    multipass_identifier: None,
  },
  discount_codes: [],
  email: "guest@haravan.com",
  financial_status: "paid",
  fulfillments: [],
  fulfillment_status: "notfulfilled",
  tags: "",
  gateway: "Thanh toán khi giao hàng (COD)",
  gateway_code: "cod",
  id: 1236954857,
  landing_site: None,
  landing_site_ref: None,
  source: "haravan_draft_order",
  line_items: [
    {
      fulfillable_quantity: 1,
      fulfillment_service: None,
      fulfillment_status: "notfulfilled",
      grams: 0,
      id: 1319685320,
      price: 2340000,
      price_original: 2340000,
      price_promotion: 0,
      product_id: 1035974155,
      quantity: 1,
      requires_shipping: True,
      sku: None,
      title: "Đồng hồ Smart watch",
      variant_id: 1079017261,
      variant_title: "Nâu",
      vendor: "Samsung",
      type: "Khác",
      name: "Đồng hồ Smart watch - Nâu",
      gift_card: False,
      taxable: True,
      tax_lines: None,
      product_exists: True,
      barcode: None,
      properties: [],
      applied_discounts: [],
      total_discount: 0,
      image: {
        src: "https: //product.hstatic.net/200000421849/product/fd_8e3c50736a99435a9272252e8ea12870.jpg",
      },
      not_allow_promotion: False,
      ma_cost_amount: 0,
    },
  ],
  name: "#100017",
  note: "88888",
  number: 1236954857,
  order_number: "#100017",
  processing_method: None,
  referring_site: "haravan_draft_order",
  refunds: [],
  shipping_address: {
    address1: None,
    address2: None,
    city: None,
    company: None,
    country: "Vietnam",
    first_name: None,
    last_name: None,
    latitude: None,
    longitude: None,
    phone: None,
    province: None,
    zip: None,
    name: "",
    province_code: None,
    country_code: "VN",
    district_code: None,
    district: None,
    ward_code: None,
    ward: None,
  },
  shipping_lines: [{ code: None, price: 0, source: None, title: None }],
  source_name: "haravan_draft_order",
  subtotal_price: 2340000,
  tax_lines: None,
  taxes_included: False,
  token: "528cdafeee0c4117a459427d3db99aea",
  total_discounts: 0,
  total_line_items_price: 2340000,
  total_price: 2340000,
  total_tax: 0,
  total_weight: 0,
  updated_at: "2021-10-28T09:44:38.609Z",
  transactions: [
    {
      amount: 2340000,
      authorization: None,
      created_at: "2021-10-25T14:36:51.989Z",
      device_id: None,
      gateway: "Thanh toán khi giao hàng (COD)",
      id: 1096348777,
      kind: "pending",
      order_id: 1236954857,
      receipt: None,
      status: None,
      user_id: 200000905615,
      location_id: 1181286,
      payment_details: None,
      parent_id: None,
      currency: None,
      haravan_transaction_id: None,
      external_transaction_id: None,
    },
    {
      amount: 2340000,
      authorization: None,
      created_at: "2021-10-26T05:05:38.443Z",
      device_id: None,
      gateway: "Thanh toán khi giao hàng (COD)",
      id: 1096407251,
      kind: "capture",
      order_id: 1236954857,
      receipt: None,
      status: None,
      user_id: 200000905615,
      location_id: 1181286,
      payment_details: None,
      parent_id: 1096348777,
      currency: None,
      haravan_transaction_id: None,
      external_transaction_id: None,
    },
  ],
  note_attributes: [],
  confirmed_at: "2021-10-25T14:36:52.138Z",
  closed_status: "unclosed",
  cancelled_status: "uncancelled",
  confirmed_status: "confirmed",
  assigned_location_id: None,
  assigned_location_at: None,
  exported_confirm_at: None,
  user_id: 200000905615,
  device_id: None,
  location_id: 1181286,
  ref_order_id: 0,
  ref_order_number: None,
  utm_source: None,
  utm_medium: None,
  utm_campaign: None,
  utm_term: None,
  utm_content: None,
  payment_url: None,
  contact_email: "guest@haravan.com",
  order_processing_status: "confirmed",
  redeem_model: None,
};
