version: '3.5'
services:  
  # docker-lib:    
  #   container_name: docker-lib
  #   build: ./docker-lib

  app:
    container_name: haipb-bitrix24
    # depends_on:
    #   - docker-lib
    network_mode: "host"
    build: .
    volumes:
      - .:/haipb-bitrix24
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER_NAME: root
      DATABASE_PASSWORD: root