name: remote ssh and deploy
on:
  push:
    branches:
    - 'no-deploy'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd haipb/app
          git pull
          docker build -t blu_app_img .
          docker stop blu_app && docker rm blu_app
          docker run --name=blu_app -d -p 5000:5000 --add-host host.docker.internal:host-gateway blu_app_img