name: remote ssh and deploy
on:
  push:
    branches:
    - 'main'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd haipb/app
          git fetch
          git pull
          docker-compose down
          docker-compose build
          docker-compose up
          exit